spring:
  application:
    name: gateway-service

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: BOUTIQUE-SERVICE
          uri: lb://BOUTIQUE-SERVICE
          predicates:
            - Path=/api/boutique/**
        - id: COMMANDE-SERVICE
          uri: lb://COMMANDE-SERVICE
          predicates:
            - Path=/api/commande/**
        - id: PAIEMENT-SERVICE
          uri: lb://PAIEMENT-SERVICE
          predicates:
            - Path=/api/paiement/**
        - id: UTILISATEUR-SERVICE
          uri: lb://UTILISATEUR-SERVICE
          predicates:
            - Path=/api/auth/**
