spring:
  application:
    name: gateway-service

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.cloud.gateway: DEBUG
    
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: boutique-service
          uri: lb://boutique-service
          predicates:
            - Path=/api/categories/**
            - Path=/api/produits/**
        - id: commande-service
          uri: lb://commande-service
          predicates:
            - Path=/api/commande/**
            - Path=/api/panier/**
        - id: paiement-service
          uri: lb://paiement-service
          predicates:
            - Path=/api/paiement/**
            - Path=/api/facture/**
        - id: utilisateur-service
          uri: lb://utilisateur-service
          predicates:
            - Path=/api/auth/**
    
