spring:
  application:
    name: gateway-service

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.cloud.gateway: DEBUG

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        # Boutique Service
        - id: boutique-categories
          uri: lb://boutique-service
          predicates:
            - Path=/api/categories/**
        - id: boutique-produits
          uri: lb://boutique-service
          predicates:
            - Path=/api/produits/**

        # Commande Service
        - id: commande
          uri: lb://commande-service
          predicates:
            - Path=/api/commande/**
        - id: panier
          uri: lb://commande-service
          predicates:
            - Path=/api/panier/**

        # Paiement Service
        - id: paiement
          uri: lb://paiement-service
          predicates:
            - Path=/api/paiement/**
        - id: facture
          uri: lb://paiement-service
          predicates:
            - Path=/api/facture/**

        # Utilisateur Service
        - id: utilisateur-auth
          uri: lb://utilisateur-service
          predicates:
            - Path=/api/auth/**
